### ISSUE TITLE
How to get same height for all the images in the owl-carousel?

### ISSUE THREAD

**Issue by ritsraghani** [OwlCarousel2/OwlCarousel2#2199]
Some of my images are of 250px height some are 100 px.. How to adjust height to all images as same.?

**Comment by ianhobbs** [comment]
did you try applying a  img { height: 100% } and  div.image-wrapper{ height: 100px} to the wrapping div?

**Comment by gnxdev** [comment]
You can set owl-stage display as flexbox and then apply height 100% on images

```css
.owl-carousel .owl-stage {
    display: flex;
}

.owl-carousel .owl-item img {
    width: auto;
    height: 100%;
}
```
