### ISSUE TITLE
CSS-Selector for max-height when using lazyLoading on a div element.

### ISSUE THREAD

**Issue by jbez** [OwlCarousel2/OwlCarousel2#2357]
### A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.>
1. Using class .owl-lazy and  attribute data-src on a div element turns the data-src into a background-image.
However, any .owl-lazy element without a src attribute or with an empty src attribute is given a max-height of 0, therefore making i.e. divs with background-images not visible after lazy-loading.
_____________
### `<url>` - a link to the reduced test case.
- https://codepen.io/anon/pen/aKBYYL

_____________
### Any other information you want to share that is relevant to the issue being reported.

I'm fairly certain it would be this selector, because it applies for all elements with class owl-lazy with no src attribute, not only img tags:
https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/src/scss/_lazyload.scss#L16

**Comment by jverdeyen** [comment]
@jbez any news?
How did you resolved this?

```scss
.owl-carousel {
    .owl-item {
        .owl-lazy[src^=""], .owl-lazy:not([src]) {
            max-height: none !important;
        }
    }
}
```
