### ISSUE TITLE
Shadows around owl item being cut off

### ISSUE THREAD

**Issue by devShamim** [OwlCarousel2/OwlCarousel2#2568]
Hi,
I am facing issues with box shadow. When I set box shadow around the owl-item it's being cut off because off overflow hidden set on owl-stage-outer. Is there any way to stop the shadows being cut off? 

TIA

**Comment by Aslam97** [comment]
Add height to `.owl-carousel .owl-stage:after` 
```
.owl-carousel .owl-stage:after {
    content: ".";
    display: block;
    clear: both;
    visibility: hidden;
    line-height: 0;
    height: 5px;
}
```

**Comment by devShamim** [comment]
Well, the problem was with the left and right shadows. like this one http://prntscr.com/qrkmn8
Your code works fine for the top and bottom, and this can be done with padding too.

**Comment by kevinpainchaud** [comment]
Hi,

I use this method:

```css
.owl-carousel .owl-stage-outer {
    height: calc(100% + 30px);
    margin: -15px;
    padding: 15px;
    width: calc(100% + 30px);
}
```

and it works pretty well :)
