### ISSUE TITLE
video iframe dupliactes

### ISSUE THREAD

**Issue by h-lennon** [OwlCarousel2/OwlCarousel2#2615]
in Demos on the official website when I'm going to https://owlcarousel2.github.io/OwlCarousel2/demos/video.html - there a stupid bug that is not allowed to lunch my project. See video: https://monosnap.com/file/tgRNO6BbOsnARZi8HwdJwZuhzPBm6H

**Comment by simongoricar** [comment]
This can be fixed by setting the icon to `display: none` when an iframe is present.

```css
.owl-video-wrapper iframe + .owl-video-play-icon {
    display: none;
}
```

Fixed with #2627
