### ISSUE TITLE
Broken in flexbox container

### ISSUE THREAD

**Issue by MichaelThessel** [OwlCarousel2/OwlCarousel2#2636]
Adding a carousel within a flexbox container breaks the container.
_____________
https://codepen.io/anon/pen/qzzJyV

**Comment by yunusga** [comment]
```css
* {
	min-width: 0;
	min-height: 0;
}
```
It`s not Owl problem. [codepen.io/anon/pen/oKjgra](https://codepen.io/anon/pen/oKjgra)
