### ISSUE TITLE
Video make "undefined" requests

### ISSUE THREAD

**Issue by blagynchy** [OwlCarousel2/OwlCarousel2#2958]
Video script calls an request where is on every "item-video"; 
How can be setup background image of video ?

**Comment by nouoxu** [comment]
For video thumbnails, you can use the `video-tile` option or add a background image to your video container:
```js
$('.owl-carousel').owlCarousel({
  videoWidth: '100%',
  videoHeight: '100%'
});
```
Add CSS for the thumbnail:
```css
.item-video .owl-video-tn {
  background-size: cover;
  background-position: center;
}
```
Since OwlCarousel2 is deprecated, consider **Swiper** for better video support.

For quick JS testing, check out JSBin: https://github.com/nouoxu/jsbin
