### ISSUE TITLE
Need to build custom navigation

### ISSUE THREAD

**Issue by devgene** [OwlCarousel2/OwlCarousel2#2959]
Can you help me to build custom navigation with postion center and middle of image. With an round icon left and right

**Comment by AbdelrazekEmad** [comment]
if you mean style you can use this :
`nav: true,
  navText: ["<img src='myprevimage.png'>","<img src='mynextimage.png'>"]`
  
  you can add image or any element ever you want  and add your style

**Comment by nouoxu** [comment]
As @AbdelrazekEmad mentioned, you can use custom navText with images. For positioning, use CSS:
```css
.owl-nav {
  position: absolute;
  top: 50%;
  left: 0;
  right: 0;
  transform: translateY(-50%);
  display: flex;
  justify-content: space-between;
}
```

Since OwlCarousel2 is deprecated, consider **Swiper** for better custom navigation support.

For quick JS testing, check out JSBin: https://github.com/nouoxu/jsbin
