### ISSUE TITLE
Need help to properly show/ hide and change styles for specific items within the carousal

### ISSUE THREAD

**Issue by sasindumendis** [OwlCarousel2/OwlCarousel2#392]
I m using plugin version 2.0.0-beta.2.4.

My carousal is initialized with following HTML and JS options; 

``` html
<nav>
   <a href="" data-filter="red">red</a>
   <a href="" data-filter="green">green</a>
   <a href="" data-filter="blue">blue</a>
   <a href="" data-filter="yellow">yellow</a>
</nav>

<div id="my-carousal" class="owl-carousel">
    <div class="item red green" style="width:250px;"><h4>1</h4></div>
    <div class="item blue" style="width:250px;"><h4>2</h4></div>
    <div class="item green blue" style="width:250px;"><h4>3</h4></div>
    <div class="item red yellow" style="width:250px;"><h4>4</h4></div>
    <div class="item yellow red green" style="width:250px;"><h4>5</h4></div>
    <div class="item blue green red" style="width:250px;"><h4>6</h4></div>
</div>
```

``` javascript
$("#my-carousel").owlCarousel({
  center: true,
  loop: true,
  autoWidth:true,
  margin:20
});
```
- I want to apply a CSS opacity to all except 3 items on the middle of the stage. I m doing something like below for now;

``` css
/*  make all items except the center item semi transparent*/
#my-carousal .owl-item:not(.center) {
  opacity: 0.2;
}
/*  then make the item next and previous to the center item opaque via JS.  */
```

Is there a way to do this without JS?

---
- The main question is though, I want to filter items by a tag when a respective button is clicked. With JS I can hide and show items on button clicks but could not find a way to reinit the carousal so the filtered item get rearranged nicely. In plugin version 1.x there was a reinit() but could not manage to do it in new version. Can anybody help with this?
